### ISSUE TITLE
Setup Devise

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#1]
The point of the Devise gem is to provide user account and authentication.

**Comment by scherztc** [comment]
https://github.com/plataformatec/devise

https://github.com/uclibs/treatment_database/commit/00d82d8af70c2881ba9e0867452d4b60608bd780

**Comment by Uzval-Mallepeddi** [comment]
Precise steps to install devise:

1) Open GemFile and add “gem ‘devise’” and bundle install to get the devise gem. 
2) Now, run the generator for scaffolding “rails g devise:install”. That’s it ! The devise gem is installed !
3) Now, there are couple of manual things that we have to take care of !
	i) Open config/environments/development.rb and add 
		“config.action_mailer.default_url_options = {host: ‘localhost’, port: 3000}“
	ii) In routes.rb make sure to have a root route pointing to some controller. Let’s say front#index 	     is your root route.
4) Now, create a model using “rails g devise MODEL_NAME”
5) And the, “rails db:migrate”, to get the schema created for the database table.
6) Generate views using “rails g devise:views”
7) Before rendering views for devise, make sure that “devise_for: users” is present in the routes.rb file which allows us to get all the routes.
8) Check all the routes using “rake routes” in the terminal and it must list all the routes available for devise gem.


Please refer to https://github.com/plataformatec/devise/ for further details !
