### ISSUE TITLE
reCAPTCHA

### ISSUE THREAD

**Issue by Uzval-Mallepeddi** [uclibs/application_portfolio#125]
- Integrate a google captcha on Request Software to prevent bots from requesting new software.

**Comment by scherztc** [comment]
I think we also need a reCaptcha on the New User Sign Up page.

- [ ] Request Software
- [ ] New User Sign Up

**Comment by scherztc** [comment]
reCaptcha keys and ids have been created and supplied to Uzval.

**Comment by scherztc** [comment]
We can close this issue when we merge, since we don't need it on sign up.
