### ISSUE TITLE
Rubocop Corrections

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#14]
modified:   bin/rails
	modified:   coverage/.resultset.json
	modified:   coverage/index.html
	modified:   db/schema.rb

Rubocop finds 20 offenses around stying. 

Run rubocop -a.  Add files. Commit changes.

**Comment by Uzval-Mallepeddi** [comment]
Generated a new configuration file by using 'rubocop --auto-gen-config' and this configuration cleared all offenses. 
https://github.com/uclibs/application_portfolio/issues/8
