### ISSUE TITLE
Sensitive Information field crashes application.

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#203]
Description : The sensitive_information field is crashing when anything is entered and submitted.

Depends ON : Nothing

Done looks like

- [ ] When I save information to the sensitive_information field it won't crash the application.
- [ ] When I save information to the sensitive_information field it will save the updated information.

**Comment by crowesn** [comment]
On which environment was this error encountered? I am unable to replicate on local.

**Comment by scherztc** [comment]
Hmm... We are having the problem on Production.  I will get you the error message.

**Comment by crowesn** [comment]
```
D, [2021-05-27T15:30:57.830273 #2431] DEBUG -- : [21c7ebf8-94ca-49ef-8937-bc6025400b45]   ^[[1m^[[36mUser Load (0.9ms)^[[0m  ^[[1m^[[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 ORDER BY `users`.`id` ASC LIMIT 1^[[0m
I, [2021-05-27T15:30:57.832133 #2431]  INFO -- : [21c7ebf8-94ca-49ef-8937-bc6025400b45] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.9ms)
F, [2021-05-27T15:30:57.832517 #2431] FATAL -- : [21c7ebf8-94ca-49ef-8937-bc6025400b45]
F, [2021-05-27T15:30:57.832539 #2431] FATAL -- : [21c7ebf8-94ca-49ef-8937-bc6025400b45] TypeError (no implicit conversion of nil into String):
F, [2021-05-27T15:30:57.832553 #2431] FATAL -- : [21c7ebf8-94ca-49ef-8937-bc6025400b45]
F, [2021-05-27T15:30:57.832590 #2431] FATAL -- : [21c7ebf8-94ca-49ef-8937-bc6025400b45] app/helpers/software_records_helper.rb:36:in `encrypt'
[21c7ebf8-94ca-49ef-8937-bc6025400b45] app/controllers/software_records_controller.rb:132:in `check_and_encrypt'
[21c7ebf8-94ca-49ef-8937-bc6025400b45] app/controllers/software_records_controller.rb:85:in `create'
```

**Comment by crowesn** [comment]
Since this isn't encountered in development env, I'm wondering if this might have to do wiht the master key implementation

https://github.com/uclibs/application_portfolio/blob/qa/app/helpers/software_records_helper.rb#L36
