### ISSUE TITLE
Install and Configure User Abilities

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#21]
There should be the ability to have a user ability roles defined.  Let's start with and Admin, Editor, and Viewer role using something like CanCan  

Manage User Abilities
	Admin	
	Editor	
	Viewers

**Comment by scherztc** [comment]
Will requires database and model modifications.

**Comment by Uzval-Mallepeddi** [comment]
Found alternate gems that are well maintained on github
1) Petergate
https://github.com/elorest/petergate
2) Pundit
https://github.com/varvet/pundit
Both of them have good community support and are stable. For now, petergate looks flexible and easy to use. Please let me know your perspective on this. :)
