### ISSUE TITLE
Coveralls is hanging in Github

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#221]
CircleCI Output : 

!/bin/bash -eo pipefail
curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"

{"done":true,"url":"https://coveralls.io/builds/39662688","jobs":4}
CircleCI received exit code 0

I also noticed that the coverall gem was pinned and we might try unpinning it.

**Comment by hortongn** [comment]
Coveralls integration works fine for the aaec repo.  Try updating the app portfolio's sepc_helper so that the simplecov and coveralls settings match aaec's spec_helper.

**Comment by scherztc** [comment]
https://github.com/lemurheavy/coveralls-public/issues/1369
https://github.com/parroty/excoveralls/pull/228/files
https://github.com/uclibs/aaec/commit/308139c9fb350f25857591b8d8334d60b2d70b48

**Comment by scherztc** [comment]
https://github.com/uclibs/aaec/blob/qa/spec/spec_helper.rb#L20-L35

**Comment by scherztc** [comment]
Look into switching to Github Actions instead of ORBs : https://github.com/marketplace/actions/coveralls-github-action

**Comment by scherztc** [comment]
https://docs.coveralls.io/integrations#official-integrations
