### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by rangarra** [uclibs/application_portfolio#233]
Description : Routing Error,  **No route matches [GET] "/file_uploads"**
I have noticed that when the root admin trying to click the cancel button during the data import process I can see the routing error. which is on **http://localhost:3000/seed/new**
To be precise, I can see that error happening only after one trial of data import, in both cases, success/failure. (When there is some result, that we can see on the **Import Result(s)** block)

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBAPPPORT-38?atlOrigin=eyJpIjoiYjZkMGFjZjc2NDY2NDlmMGJmYWFhNWZhNjIyNjhmM2IiLCJwIjoiaiJ9
