### ISSUE TITLE
Blanks in import file

### ISSUE THREAD

**Issue by crowesn** [uclibs/application_portfolio#234]
Output explicit error when blank required fields are encountered in import files.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBAPPPORT-37?atlOrigin=eyJpIjoiZjY0NDI5YWM2MGYzNDA4OGIzZmZiMDI1ZDZiYjAyYmYiLCJwIjoiaiJ9
