### ISSUE TITLE
Fix Coveralls in CircleCI build

### ISSUE THREAD

**Issue by bsp3ars** [uclibs/application_portfolio#265]
Currently, we are able to build the application using the cimg (ruby w/ browsers) from CircleCI, but the coveralls information is not being uploaded, which results in the following error at the end of the build:

```
{"error":"No build matching CI build number 443 found"}
CircleCI received exit code 0
```
This may be fixed with something as simple as using the coveralls orb from [CIrcleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls), or it may be a more in-depth issue.

**Comment by hortongn** [comment]
@bsp3ars See https://github.com/uclibs/treatment_database/pull/326 to see how @crowesn resolved this for the treatment app.

**Comment by crowesn** [comment]
CircleCI is now showing success status on coveralls upload task:
```
{"done":true,"url":"https://coveralls.io/builds/59744673","jobs":1}
CircleCI received exit code 0
```

Closing this issue as obsolete.
