### ISSUE TITLE
Add warnings when deploying

### ISSUE THREAD

**Issue by bsp3ars** [uclibs/application_portfolio#266]
Look into ways of warning when deploying via Capistrano.

- Message containing the project name, branch being pushed, user, etc
- Verification of approval for deployment
- Etc.

**Comment by crowesn** [comment]
Do we want this information in the form of an email? or output to the shell during deployment?

**Comment by crowesn** [comment]
Add confirmation check before executing deploy e.g. Press Y to confirm.

**Comment by crowesn** [comment]
https://github.com/jinzhu/capistrano-confirm

**Comment by crowesn** [comment]
https://capistranorb.com/documentation/getting-started/user-input/
