### ISSUE TITLE
Upgrade to Rails version 6.1.x and Upgrade to Ruby version 3.1.x

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#276]

**Comment by haitzlm** [comment]
WARNING: ruby-2.7.5 is nearing its end of life.
It only receives critical security updates, no bug fixes.

FYI

**Comment by hortongn** [comment]
@scherztc This issue has been resolved, correct?

**Comment by haitzlm** [comment]
Ruby is on ruby '3.0.5' rails is 6.1

**Comment by haitzlm** [comment]
my mistake, as i said, it is not using 2.7.5. Just the Docker file needed to be updated.

**Comment by scherztc** [comment]
https://github.com/uclibs/application_portfolio/pull/285
