### ISSUE TITLE
Add Modules / Plugins / Themes Checkbox to Software Record

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#282]

**Comment by crowesn** [comment]
Is this just one checkbox "Modules / Plugins / Themes" ?

**Comment by crowesn** [comment]
@scherztc Can you add some more details to this issue?

**Comment by haitzlm** [comment]
For this issue- are we wanting to track which apps have modules/plugins/themes that must be updated, or the last time these were updated? If so, they should probably separated out... as at least in Wordpress and Omeka plugins will require many more updates than a theme. I do think it could be one checkbox for themes and one for Plugins/Modules, as plugins and modules are really the same thing just the label is different in different applications. And we would also need a date field to show the last update. 
If we just want to keep track of which software has these things I would still separate out, but eliminate the date field.
