### ISSUE TITLE
QA deploy fails missing linux platform in lock file

### ISSUE THREAD

**Issue by crowesn** [uclibs/application_portfolio#302]
Caused by:
SSHKit::Command::Failed: bundle exit status: 16
bundle stdout: Nothing written
bundle stderr: [DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '/opt/webapps/application_portfolio/shared/vendor/bundle'`, and stop using this flag
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local without 'development test'`, and stop using this flag
Your bundle only supports platforms ["x86_64-darwin-19", "x86_64-darwin-21"] but
your local platform is x86_64-linux. Add the current platform to the lockfile
with `bundle lock --add-platform x86_64-linux` and try again.

Tasks: TOP => deploy:updated => bundler:install
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as apache@libappstest.libraries.uc.edu: bundle exit status: 16
bundle stdout: Nothing written
bundle stderr: [DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '/opt/webapps/application_portfolio/shared/vendor/bundle'`, and stop using this flag
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local without 'development test'`, and stop using this flag
Your bundle only supports platforms ["x86_64-darwin-19", "x86_64-darwin-21"] but
your local platform is x86_64-linux. Add the current platform to the lockfile
with `bundle lock --add-platform x86_64-linux` and try again.

**Comment by scherztc** [comment]
This is complete.
https://github.com/uclibs/application_portfolio/blob/qa/Gemfile.lock#L379
