### ISSUE TITLE
Update error/404 page contact information

### ISSUE THREAD

**Issue by hortongn** [uclibs/application_portfolio#338]
The current error/404 page says to contact Glen Horton or Thomas Scherz.  Update to contact uclappdev@uc.edu

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBAPPPORT-11?atlOrigin=eyJpIjoiMDBmYmQ5NTgwNzIwNDQxMzg4MGE2ODMyZjNkMWU2MWEiLCJwIjoiaiJ9
