### ISSUE TITLE
Testing:  rspec spec

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#36]
I should be able to run individual test or whole directories of test.  When I try to run rspec spec, I get the following error:

An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require 'coveralls'

Gem::ConflictError:
  Unable to activate coveralls-0.8.23, because simplecov-0.17.1 conflicts with simplecov (~> 0.16.1)
# ./spec/spec_helper.rb:27:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- coveralls
#   ./spec/spec_helper.rb:27:in `<top (required)>'

**Comment by scherztc** [comment]
Due to my multiple projects, I had some conflicts with my version of coveralls. 

I uninstalled both coveralls and simplecov gem.  Bundle installed and then made sure that I am was running bundle exec rspec spec.

**Comment by rsmithlal** [comment]
> Due to my multiple projects, I had some conflicts with my version of coveralls.
> 
> I uninstalled both coveralls and simplecov gem. Bundle installed and then made sure that I am was running bundle exec rspec spec.

Thank you, this solved it for me too! Had to manually uninstall both gems and rebundle to remove the extra version that was left over from a previous bundle
