### ISSUE TITLE
Hyperlinks should have underlines

### ISSUE THREAD

**Issue by hortongn** [uclibs/application_portfolio#369]
When content such as a note has a hyperlink in it, the link is currently displayed like normal text until you hover over it with your cursor.  This makes it hard to spot links.

Change:
Hyperlinks in content should always be underlined.  This is probably just a CSS change.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBAPPPORT-13?atlOrigin=eyJpIjoiMjAzNWFjNGEzYzJiNDAyYThhNThkOTI0MjIyYWQwNDgiLCJwIjoiaiJ9
