### ISSUE TITLE
Use abilities (refactor)

### ISSUE THREAD

**Issue by hortongn** [uclibs/application_portfolio#370]
Given this application has users with different roles, we should be using the cancancan gem with an Abilities class like our other apps.  This will clean up some of the custom logic we have.

**Comment by scherztc** [comment]
Currently, we use Petergate : https://github.com/elorest/petergate

What does CanCan give us that Petergate doesn't?

**Comment by hortongn** [comment]
@scherztc The petergate gems hasn't been updated in a few years.  Better to use cancancan that has active development.  I'm not saying we need to switch now.  I'm just creating the issue so we remember to do it at some point.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBAPPPORT-32?atlOrigin=eyJpIjoiNjk0YzNiNmFhNTc3NDBmZGI4NTM5MGRmMDlkN2ZlNGIiLCJwIjoiaiJ9
