### ISSUE TITLE
Run Application in RAILS_ENV=production

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#72]
First Error : application.rb:585:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit` (ArgumentError)

**Comment by Uzval-Mallepeddi** [comment]
When i tried to set the env path to "RAILS_MASTER_KEY" and assign it with the key and run the server in production mode, i get the following error. 
_/Users/mallepvl/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/message_encryptor.rb:206:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)_

**Comment by scherztc** [comment]
We will also need to create a release branch.
Version tagging.
