### ISSUE TITLE
Create New Software Record Form (Owner)

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#77]
This form should have a limited set of fields that only the Product Owner would want to see.

The fields should include:

**Comment by scherztc** [comment]
Title
Description
Status
Date implemented
Date of upgrade
Tentative date implemented
Vendor
Departments
Product owners
Url
User seats
Annual fees
Support contract
Hosting environment
Current version
Notes
Business value

**Comment by Uzval-Mallepeddi** [comment]
@scherztc 
Thomas, i just realized the fact that owner cannot create a software record but only can request a software record. To create a software record, we must need software type and vendor record. Software Type should be included in above list. As an owner can request the software record, he will not have the privilege of selecting from available vendor types. Instead "University of Cincinnati" is selected by default. 

Also, could you please let me know why "developers" and "tech leads" are not included in this owner form ? (Just curious to understand the reasoning.. ;) )
