### ISSUE TITLE
Create New Software Record Form (Manager)

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#78]
This form should be used by Tech Leads and Developers.

It should have the following fields:

**Comment by scherztc** [comment]
Title
Description
Status
Date implemented
Date of upgrade
Tentative date implemented
Software type
Vendor
Developers
Tech leads
Product owners
Languages used
Url
Hosting environment
Current version
Notes
User seats
Support contract

**Comment by Uzval-Mallepeddi** [comment]
@scherztc 
Thomas, I'm curious to know your stand on field "Sensitive Information" for both manager and owner forms. Both manager and product owners can have access to sensitive information like private keys, passwords e.t.c. So, wouldn't it make sense to allow "sensitive information" field allowed for manager, owner and admin ?
PS: I doubt if a manager/product owner has passwords and all other sensitive information.
Need your inputs on this !
