### ISSUE TITLE
Create a New Project checklist for people starting a new development project (e.g. scope, accessibility, security, scans, hosting, etc.)

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#95]
Application Portfolio Enhancement - Create a New Project checklist for people starting a new development project (e.g. scope, accessibility, security, scans, hosting, etc.)

**Comment by hortongn** [comment]
Also track Office of General Council approvals.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBAPPPORT-40?atlOrigin=eyJpIjoiYWViYmQ5M2I2YmNlNDA1ZmIxY2JjYTljYTJkZjgyNTEiLCJwIjoiaiJ9
